module.exports = [
  {
    source: "/GalleryPhotos/SacredHeartFinal.jpg",
    lowRes: "/LowResGalleryPhotos/SacredHeartFinal_LowRes.jpg",
    title: "Sacred Heart",
    description: 'Oil on Canvas, 18"x24"',
  },
  {
    source: "/GalleryPhotos/DominusEstFinal.jpg",
    lowRes: "/LowResGalleryPhotos/DominusEstFinal_LowRes.jpg",
    title: "Dominus Est",
    description: 'Oil on Canvas, 18"x24"',
  },
  {
    source: "/GalleryPhotos/BlessedAlbertoMarvelliFinal.jpg",
    lowRes: "/LowResGalleryPhotos/BlessedAlbertoMarvelliFinal_LowRes.jpg",
    title: "Blessed Alberto Marvelli",
    description: 'Pencil on Paper, 11"x14"',
  },
  {
    source: "/GalleryPhotos/SeaOfGalileeFinal.jpg",
    lowRes: "/LowResGalleryPhotos/SeaOfGalileeFinal_LowRes.jpg",
    title: "Sea of Galilee",
    description: 'Oil on Canvas, 18"x24"',
  },
  {
    source: "/GalleryPhotos/ImmaculateConception.png",
    lowRes: "/LowResGalleryPhotos/ImmaculateConception_LowRes.png",
    title: "Study of 'Immaculate Conception'",
    description: 'Watercolor on Paper, 17.5"x29"',
  },
  {
    source: "/GalleryPhotos/ChristsHeadRembrandt.jpg",
    lowRes: "/LowResGalleryPhotos/ChristsHeadRembrandt_LowRes.jpg",
    title: "Study of 'Head of Christ' by Rembrandt",
    description: 'Pencil on Paper, 5"x7"',
  },
  {
    source: "/GalleryPhotos/IBelieveInLoveFinal.jpg",
    lowRes: "/LowResGalleryPhotos/IBelieveInLoveFinal_LowRes.jpg",
    title: "St. Thérèse of Liseux",
    description: 'Pencil on Paper, 9"x12"',
  },
  {
    source: "/GalleryPhotos/CruxFidelis.jpg",
    lowRes: "/LowResGalleryPhotos/CruxFidelis_LowRes.jpg",
    title: "Crux Fidelis",
    description: 'Pencil on Paper, 9"x12"',
  },
  {
    source: "/GalleryPhotos/AllOrNothingFinal.jpg",
    lowRes: "/LowResGalleryPhotos/AllOrNothingFinal_LowRes.jpg",
    title: "Sister Clare Crockett",
    description: 'Pencil on Paper, 9"x12"',
  },
  {
    source: "/GalleryPhotos/OLMM.jpg",
    lowRes: "/LowResGalleryPhotos/OLMM_LowRes.jpg",
    title: "Our Lady of the Miraculous Medal",
    description: 'Liquid Watercolor on Paper, 5"x7"',
  },
  {
    source: "/GalleryPhotos/SicDeus.jpg",
    lowRes: "/LowResGalleryPhotos/SicDeus_LowRes.jpg",
    title: "Study of 'Sic Deus Dilexit Mundum'",
    description: 'Liquid Watercolor on Paper, 5"x7"',
  },
  {
    source: "/GalleryPhotos/PhilipNeri.jpg",
    lowRes: "/LowResGalleryPhotos/PhilipNeri_LowRes.jpg",
    title: "Study of 'St. Philip Neri in Ecstasy' by Guido Remi",
    description: 'Liquid Watercolor on Paper, 5"x7"',
  },
  {
    source: "/GalleryPhotos/StPaul.jpg",
    lowRes: "/LowResGalleryPhotos/StPaul_LowRes.jpg",
    title: "Study of 'St. Paul' by Pompeo Batoni",
    description: 'Liquid Watercolor on Paper, 5"x7"',
  },

  {
    source: "/GalleryPhotos/AnthonyFinal.jpg",
    lowRes: "/LowResGalleryPhotos/AnthonyFinal_LowRes.jpg",
    title: "Study of 'St. Anthony of Padua' by Bartolome Esteban Murillo",
    description: 'Graphite on toned paper, 9"x12"',
  },
  {
    source: "/GalleryPhotos/CatherineFinal.jpg",
    lowRes: "/LowResGalleryPhotos/CatherineFinal_LowRes.jpg",
    title: "Study of 'St. Catherine of Siena' by Baldassare Franceschini",
    description: 'Graphite on toned paper, 9"x12"',
  },
  {
    source: "/GalleryPhotos/KolbeFinal.jpg",
    lowRes: "/LowResGalleryPhotos/KolbeFinal_LowRes.jpg",
    title: "Maximillian Kolbe",
    description: 'Graphite on Paper, 5"x8.5"',
  },
  {
    source: "/GalleryPhotos/PadrePio.jpg",
    lowRes: "/LowResGalleryPhotos/PadrePio_LowRes.jpg",
    title: "Padre Pio",
    description: 'Coffee on Paper, 9"x12"',
  },
];
