module.exports = [
  {
    id: 1001,
    link: "/product/sacred-heart",
    title: "Sacred Heart Print",
    shortDesc: "Print of the Sacred Heart signed by the artist",
    thumbnail: "/SacredHeartSquare.jpg",
    image: "/SacredHeart.jpg",
    price: 350,
    fullDesc: "",
    stock: 1,
    category: "oil",
  },
  {
    id: 1001,
    title: "Sacred Heart Print1",
    shortDesc:
      "Print of the Sacred Heart signed by the artist. Print of the Sacred Heart signed by the artist. Print of the Sacred Heart signed by the artist Print of the Sacred Heart signed by the artist Print of the Sacred Heart signed by the artist",
    thumbnail: "/SacredHeartSquare.jpg",
    image: "/SacredHeart.jpg",
    price: 350,
    fullDesc: "",
    stock: 1,
    category: "oil",
  },
  {
    id: 1001,
    title: "Sacred Heart Print2",
    shortDesc: "Print of the Sacred Heart signed by the artist",
    thumbnail: "/SacredHeartSquare.jpg",
    image: "/SacredHeart.jpg",
    price: 350,
    fullDesc: "",
    stock: 1,
    category: "oil",
  },
  {
    id: 1001,
    title: "Sacred Heart Print3",
    thumbnail: "/SacredHeartSquare.jpg",
    shortDesc: "Print of the Sacred Heart signed by the artist",
    image: "/SacredHeart.jpg",
    price: 350,
    fullDesc: "",
    stock: 1,
    category: "oil",
  },
];
